CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS elo (
    username TEXT PRIMARY KEY,
    elo_score INTEGER NOT NULL DEFAULT 1000
);